#!/usr/bin/env python3
"""HDAR Attestation Verifier — verify GitHub artifact attestations on Host B reports.

This closes the largest remaining cryptographic gap identified in TRUST_BOUNDARY.md:
Host B origin authentication. The audit stated:

    "The verifier authenticates Host A well: E1 manifest integrity, Ed25519 owner
     signature, workspace hashes, parent manifest linkage, preserved shared files.
     But Host B identity remains weak. Fields such as hostname, platform string,
     nonce, timestamps, and platforms_differ are generated by the Host B program.
     They are evidence inside the report, not external proof of the report's origin."

GitHub artifact attestations solve this. The `actions/attest@v4` action in the
reproduction_matrix.yml workflow generates Sigstore-signed attestations that bind
each Host B report to:
  - the GitHub repository
  - the specific workflow run
  - the commit SHA
  - the runner environment
  - the artifact digest

This tool verifies those attestations using `gh attestation verify`, which checks
the Sigstore signature against the public-good transparency log.

Usage:

    python3 verify_attestations.py \\
        --report host_b_output/host_b_report.json \\
        --repository overandor/hdar-cross-platform-proof

    # Verify multiple reports:
    python3 verify_attestations.py \\
        --report ubuntu-24.04/host_b_report.json \\
        --report ubuntu-22.04/host_b_report.json \\
        --report macos-14/host_b_report.json \\
        --repository overandor/hdar-cross-platform-proof

    # Also verify E2 capsule attestations:
    python3 verify_attestations.py \\
        --report ubuntu-24.04/host_b_report.json \\
        --e2-tar ubuntu-24.04/capsule_epoch_2.tar.gz \\
        --repository overandor/hdar-cross-platform-proof

Prerequisites:
    - GitHub CLI (gh) installed and authenticated
    - The attestations must have been generated by the workflow

What this proves:
    - The Host B report was produced by a GitHub Actions workflow run in the
      specified repository, at the specified commit, on a GitHub-hosted runner.
    - The report has not been modified since attestation (digest binding).
    - The attestation is signed by Sigstore with a short-lived certificate
      issued via GitHub OIDC federation.

What this does NOT prove:
    - The runner was not compromised (attestation proves origin, not integrity
      of the execution environment itself).
    - The workflow logic was correct (attestation proves the workflow ran, not
      that the workflow did the right thing).
    - Independent operation (the repository owner still controls the workflow).
"""
from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path

CHUNK_SIZE = 1024 * 1024


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(CHUNK_SIZE), b""):
            h.update(chunk)
    return h.hexdigest()


def verify_attestation(subject_path: Path, repository: str) -> dict:
    """Verify a GitHub artifact attestation using `gh attestation verify`.

    Returns a dict with:
      - ok: whether verification succeeded
      - subject_path: the path to the artifact
      - subject_sha256: the SHA-256 of the artifact
      - repository: the repository used for verification
      - output: the raw gh CLI output
      - attestation_count: number of attestations found
    """
    subject_sha256 = sha256_file(subject_path)

    cmd = [
        "gh", "attestation", "verify", str(subject_path),
        "--repo", repository,
        "--format", "json",
    ]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
    except FileNotFoundError:
        return {
            "ok": False,
            "subject_path": str(subject_path),
            "subject_sha256": subject_sha256,
            "repository": repository,
            "error": "gh CLI not found. Install: https://cli.github.com/",
            "output": "",
            "attestation_count": 0,
        }
    except subprocess.TimeoutExpired:
        return {
            "ok": False,
            "subject_path": str(subject_path),
            "subject_sha256": subject_sha256,
            "repository": repository,
            "error": "gh attestation verify timed out",
            "output": "",
            "attestation_count": 0,
        }

    output = result.stdout + result.stderr
    attestation_count = 0
    if result.returncode == 0 and result.stdout:
        try:
            data = json.loads(result.stdout)
            if isinstance(data, list):
                attestation_count = len(data)
            elif isinstance(data, dict):
                attestation_count = 1
        except json.JSONDecodeError:
            # Non-JSON output (older gh versions) — count lines as a rough proxy
            attestation_count = output.count("attestation") if output else 0

    return {
        "ok": result.returncode == 0,
        "subject_path": str(subject_path),
        "subject_sha256": subject_sha256,
        "repository": repository,
        "output": output.strip(),
        "attestation_count": attestation_count,
        "exit_code": result.returncode,
    }


def extract_attestation_metadata(subject_path: Path, repository: str) -> dict:
    """Download and parse attestation metadata for richer evidence binding.

    Uses `gh attestation download` to fetch the attestation bundle, then
    extracts the workflow run ID, commit SHA, and signer identity from the
    in-toto statement.
    """
    import tempfile

    with tempfile.TemporaryDirectory() as tmpdir:
        bundle_path = Path(tmpdir) / "attestation.sigstore.json"
        cmd = [
            "gh", "attestation", "download", str(subject_path),
            "--repo", repository,
            "-o", str(bundle_path),
        ]
        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
        except (FileNotFoundError, subprocess.TimeoutExpired):
            return {"ok": False, "error": "gh CLI unavailable or timed out"}

        if result.returncode != 0 or not bundle_path.exists():
            return {"ok": False, "error": result.stderr.strip() or "download failed"}

        try:
            bundle = json.loads(bundle_path.read_text())
        except json.JSONDecodeError:
            return {"ok": False, "error": "attestation bundle is not valid JSON"}

        # The sigstore bundle format varies; extract what we can
        metadata = {"ok": True, "bundle_size": bundle_path.stat().st_size}

        # Try to extract the in-toto statement from the bundle
        if isinstance(bundle, list) and len(bundle) > 0:
            bundle = bundle[0]

        # Look for common fields in the sigstore bundle
        if isinstance(bundle, dict):
            # The statement is typically in bundle.message or bundle.content
            for key in ("message", "content", "statement"):
                if key in bundle:
                    try:
                        if isinstance(bundle[key], str):
                            statement = json.loads(bundle[key])
                        else:
                            statement = bundle[key]
                        if isinstance(statement, dict):
                            predicate = statement.get("predicate", {})
                            if isinstance(predicate, dict):
                                builder = predicate.get("builder", {})
                                invocation = predicate.get("invocation", {})
                                metadata["workflow"] = {
                                    "name": invocation.get("config", {}).get("source", ""),
                                    "build_config": invocation.get("config", {}),
                                    "builder_id": builder.get("id", ""),
                                    "build_type": predicate.get("buildType", ""),
                                }
                                metadata["source"] = predicate.get("source", {})
                                metadata["materials"] = predicate.get("materials", [])
                    except (json.JSONDecodeError, TypeError, KeyError):
                        pass

        return metadata


def main() -> int:
    ap = argparse.ArgumentParser(description="HDAR Attestation Verifier — verify GitHub artifact attestations on Host B reports")
    ap.add_argument("--report", action="append", default=[],
                    help="Path to a Host B report JSON (can specify multiple)")
    ap.add_argument("--e2-tar", action="append", default=[],
                    help="Path to an E2 capsule tar.gz (optional, must match --report order)")
    ap.add_argument("--archive", action="append", default=[],
                    help="Path to a Host B evidence archive tar.gz (alternative to --report/--e2-tar)")
    ap.add_argument("--repository", required=True,
                    help="GitHub repository (owner/repo) that generated the attestations")
    ap.add_argument("--extract-metadata", action="store_true",
                    help="Also download and parse attestation metadata for richer evidence")
    args = ap.parse_args()

    if not args.report and not args.archive:
        ap.error("at least one of --report or --archive is required")

    print("=" * 70)
    print("HDAR Attestation Verifier")
    print("=" * 70)
    print(f"  Repository: {args.repository}")
    print(f"  Reports: {len(args.report)}")
    print(f"  E2 tars: {len(args.e2_tar)}")
    print(f"  Archives: {len(args.archive)}")
    print()

    all_ok = True
    results = []

    # Verify evidence archives (single attestation per archive)
    for i, archive_path in enumerate(args.archive):
        archive = Path(archive_path)
        print(f"{'─' * 70}")
        print(f"Archive {i+1}/{len(args.archive)}: {archive}")
        print(f"  SHA-256: {sha256_file(archive)}")

        print(f"  Verifying GitHub artifact attestation on evidence archive...")
        result = verify_attestation(archive, args.repository)
        results.append({"type": "evidence-archive", "path": str(archive), **result})

        status = "PASS" if result["ok"] else "FAIL"
        print(f"  [{status}] Evidence archive attestation valid")
        if result["ok"]:
            print(f"    Attestations found: {result['attestation_count']}")
            print(f"    Repository: {args.repository}")
        else:
            print(f"    Error: {result.get('error', result.get('output', 'unknown'))}")
            all_ok = False

        if args.extract_metadata and result["ok"]:
            print(f"  Extracting attestation metadata...")
            metadata = extract_attestation_metadata(archive, args.repository)
            if metadata.get("ok"):
                print(f"    Bundle size: {metadata.get('bundle_size', 'unknown')} bytes")
            print()

    # Verify individual reports (legacy mode)
    # Pad e2_tars to match reports
    e2_tars = args.e2_tar + [None] * (len(args.report) - len(args.e2_tar))

    for i, (report_path, e2_path) in enumerate(zip(args.report, e2_tars)):
        report = Path(report_path)
        print(f"{'─' * 70}")
        print(f"Report {i+1}/{len(args.report)}: {report}")
        print(f"  SHA-256: {sha256_file(report)}")

        # Verify report attestation
        print(f"  Verifying GitHub artifact attestation...")
        result = verify_attestation(report, args.repository)
        results.append({"type": "report", "path": str(report), **result})

        status = "PASS" if result["ok"] else "FAIL"
        print(f"  [{status}] Report attestation valid")
        if result["ok"]:
            print(f"    Attestations found: {result['attestation_count']}")
            print(f"    Repository: {args.repository}")
        else:
            print(f"    Error: {result.get('error', result.get('output', 'unknown'))}")
            all_ok = False

        # Verify E2 capsule attestation if provided
        if e2_path:
            e2 = Path(e2_path)
            if e2.exists():
                print(f"  E2 capsule: {e2}")
                print(f"  E2 SHA-256: {sha256_file(e2)}")
                print(f"  Verifying E2 attestation...")
                e2_result = verify_attestation(e2, args.repository)
                results.append({"type": "e2-capsule", "path": str(e2), **e2_result})
                e2_status = "PASS" if e2_result["ok"] else "FAIL"
                print(f"  [{e2_status}] E2 capsule attestation valid")
                if not e2_result["ok"]:
                    all_ok = False
            else:
                print(f"  E2 capsule not found: {e2}")

        # Extract metadata if requested
        if args.extract_metadata and result["ok"]:
            print(f"  Extracting attestation metadata...")
            metadata = extract_attestation_metadata(report, args.repository)
            if metadata.get("ok"):
                print(f"    Bundle size: {metadata.get('bundle_size', 'unknown')} bytes")
                if "workflow" in metadata:
                    wf = metadata["workflow"]
                    print(f"    Workflow: {wf.get('name', 'unknown')}")
                    print(f"    Builder ID: {wf.get('builder_id', 'unknown')}")
                    print(f"    Build type: {wf.get('build_type', 'unknown')}")
                if "source" in metadata:
                    print(f"    Source: {metadata['source']}")
            else:
                print(f"    Metadata extraction failed: {metadata.get('error', 'unknown')}")

        # Cross-check: the report's github_workflow field should match the
        # attestation's repository
        try:
            report_data = json.loads(report.read_text())
            gh_workflow = report_data.get("github_workflow", {})
            if gh_workflow:
                reported_repo = gh_workflow.get("repository", "")
                if reported_repo and reported_repo != args.repository:
                    print(f"  [WARN] Report says repository={reported_repo} but verifying against {args.repository}")
                else:
                    print(f"  [PASS] Report github_workflow.repository matches attestation repository")
        except (json.JSONDecodeError, KeyError):
            pass

        print()

    # Summary
    print("=" * 70)
    print("ATTESTATION VERIFICATION SUMMARY")
    print("=" * 70)
    passed = sum(1 for r in results if r["ok"])
    failed = sum(1 for r in results if not r["ok"])
    print(f"  Subjects verified: {len(results)}")
    print(f"  Passed: {passed}")
    print(f"  Failed: {failed}")
    print(f"  Verdict: {'ALL ATTESTATIONS VALID — Host B origin authenticated by GitHub Sigstore' if all_ok else 'ATTESTATION FAILURES — Host B origin NOT authenticated'}")
    print()
    print("  What this proves:")
    if all_ok:
        print("    - Each Host B report was produced by a GitHub Actions workflow")
        print(f"      in {args.repository}")
        print("    - The report has not been modified since attestation (digest binding)")
        print("    - The attestation is signed by Sigstore with a short-lived certificate")
        print("      issued via GitHub OIDC federation")
        print()
        print("  What this does NOT prove:")
        print("    - The runner was not compromised (attestation proves origin, not")
        print("      integrity of the execution environment itself)")
        print("    - Independent operation (the repository owner controls the workflow)")
    print()
    return 0 if all_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
